# Generated by Django 2.1 on 2019-09-14 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sith_recruiting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitsResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sith_recruiting.Trial')),
            ],
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
