# Generated by Django 2.1 on 2019-09-14 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sith_recruiting', '0003_auto_20190914_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sith_recruiting.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='recruit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sith_recruiting.Recruit'),
        ),
    ]
