# Generated by Django 2.1 on 2019-09-15 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sith_recruiting', '0004_auto_20190914_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruitsresult',
            name='recruit',
        ),
        migrations.RemoveField(
            model_name='recruitsresult',
            name='trial',
        ),
        migrations.DeleteModel(
            name='RecruitsResult',
        ),
    ]
